### ISSUE TITLE
Dockerfile w/  g++ 4.1/ ubuntu16.04/ opencv2.4.9

### ISSUE THREAD

**Issue by AnaRhisT94** [k-miracle/Deeplidar_v2#1]
Hi @k-miracle ,
Would love to know if you've a Dockerfile with ( g++ 4.1/ ubuntu16.04/ opencv2.4.9 )

I'm still working on getting Docker to work, pretty new to this.

Thank you for this amazing repo., will update with my training results too later on this week.

**Comment by AnaRhisT94** [comment]
Hi @k-miracle ,
After installing opencv 2.4.9 and Ubuntu 16.04, I'm using another g++4.5 and getting the following error:
```
Compilling......
g++ -std=c++11 -O1 -g -w -fopenmp -o count_main.app .//tool.o -lstdc++ `pkg-config --cflags --libs opencv`
.//tool.o: In function `main':
/workspace/surface_normal/tool.cpp:1036: undefined reference to `cv::imread(std::string const&, int)'
/workspace/surface_normal/tool.cpp:1042: undefined reference to `cv::imwrite(std::string const&, cv::_InputArray const&, std::vector<int, std::allocator<int> > const&)'
collect2: error: ld returned 1 exit status
Makefile:24: recipe for target 'all' failed
make: *** [all] Error 1

```

Any ideas how to solve it?

**Comment by wassryan** [comment]
@AnaRhisT94 Hi, you can find a docker with opencv2.4.9 in [dockerhub](https://hub.docker.com/)
